### ISSUE TITLE
"Install LWT Demo Database" does not work

### ISSUE THREAD

**Issue by lwt-project** [andreask7/lwt#12]
Fatal Error in SQL Query: LOAD DATA INFILE '/var/folders/h0/sj_tsts11b3_w66mzclmp0yh0000gn/T/lwt/tmpti.txt' INTO TABLE temptextitems FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' (@c) set TiOrder = if(@c="\r",@a,@a:=@a+1), TiText = @c, TiSeID = if(@c="\r",@b:=@b+1,@b),TiWordCount=(!(@c rlike '[^\\x{0590}-\\x{05FF}]+')), TiCount = IF(@c="\r",(@d:= 0), (@d:=@d+CHAR_LENGTH(@c))+1-CHAR_LENGTH(@c))

Error Code & Message: [1139] Got error 'invalid character range' from regexp

**Comment by andreask7** [comment]
Hello and thank you for reporting the bugs,
I get the same error, if I don't escape  '\x{0590}' and '\x{05FF}'. I used the function 'convert_string_to_sqlsyntax()' to escape the regexp. I have uploaded some changes for testing.
Andreas
