### ISSUE TITLE
Arabic comma not accepted by Split sentences field

### ISSUE THREAD

**Issue by Zireael07** [andreask7/lwt#21]
This is a massive annoyance. I tried both the Unicode symbol {060C} and the character itself, still results in it being parsed as part of the word. Updated the language definition several times, forced reparsing...

See the sample paragraph
وَرَغْمَ تَوْقِيعِ كَثِيرٍ مِنْ دُوَلِ الْعَالَمِ عَلَى اتِّفَاقِيَّاتٍ دَوْلِيَّةٍ لِلْحَدِّ مِنَ الِانْبِعَاثَاتِ الْغَازِيَّةِ الضَّارَّةِ بِبِيئَةِ الْأَرْضِ، مَا زَالَ مُعَدَّلُ تَرَاكُمِ الْغَازَاتِ الدَّفِيئَةِ فِي الْغِلَافِ الْجَوِّيِّ آخِذًا فِي التَّزَايُدِ، وَيُتَوَقَّعُ أَنْ يُسَبِّبَ الِاحْتِبَاسُ الْحَرَارِيُّ زِيَادَةً فِي دَرَجَةِ حَرَارَةِ الْأَرْضِ قَدْ تَصِلُ إِلَى 4.8 دَرَجَاتٍ مِئَوِيَّةٍ بِحُلُولِ عَامِ 2100.

It has two Arabic commas in it, hence a perfect example for testing.

EDIT: And just to be clear, replicated it on vanilla LWT, so it's not your fault :P

**Comment by andreask7** [comment]
You could try the following 'RegExp Word Characters':
`\x{621}-\x{63F}\x{641}-\x{66F}\x{671}-\x{6D3}\x{6D5}\x{6DE}-\x{6FF}`
It doesn't include the comma.

**Comment by Zireael07** [comment]
Thanks, that fixes it!
I guess the Language Wizard output should be updated to your suggestion?

**Comment by andreask7** [comment]
I'll update the Language Wizard. Should the arabic numbers be parsed as terms, so that you can 'translate/romanize' them. What's you opinion?

**Comment by Zireael07** [comment]
I would exclude them as default but make a note in info.html explaining about the other, more beginner friendly option. (My rationale is I guess most users are fairly advanced - the beginners in a given language are going to be a minority)
