### ISSUE TITLE
Fatal Error in SQL Query: LOAD DATA LOCAL INFILE   when importing from a feed....

### ISSUE THREAD

**Issue by dif1754** [andreask7/lwt#24]
This is LWT 1.6.28 (April 07 2016)
Database: learning-with-texts on localhost / Default Table Set / Size: 8.1 MB

+++ "Zum Tod von Hans-Dietrich Genscher" added! +++

Fatal Error in SQL Query: LOAD DATA LOCAL INFILE 'C:\\Users\\Cristian\\AppData\\Local\\Temp/tmpti.txt' INTO TABLE temptextitems FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' (@c) set TiOrder = if(@c="\r",@a,@a:=@a+1), TiText = @c, TiSeID = if(@c="\r",@b:=@b+1,@b),TiWordCount=('¶.!?:;' not like concat("%",@c,"%")) and (!(@c rlike '[^\\-\'a-zA-ZÀ-ÖØ-öø-ȳЀ-ӹ]+')), TiCount = IF(@c="\r",(@d:= 0), (@d:=@d+CHAR_LENGTH(@c))+1-CHAR_LENGTH(@c))
Error Code & Message: [1139] Got error 'invalid character range' from regexp
Backtrace:

#0  do_mysqli_query(LOAD DATA LOCAL INFILE 'C:\\Users\\Cristian\\AppData\\Local\\Temp/tmpti.txt' INTO TABLE temptextitems FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' (@c) set TiOrder = if(@c="\r",@a,@a:=@a+1), TiText = @c, TiSeID = if(@c="\r",@b:=@b+1,@b),TiWordCount=('¶.!?:;' not like concat("%",@c,"%")) and (!(@c rlike '[^\\-\'a-zA-ZÀ-ÖØ-öø-ȳЀ-ӹ]+')), TiCount = IF(@c="\r",(@d:= 0), (@d:=@d+CHAR_LENGTH(@c))+1-CHAR_LENGTH(@c))) called at [C:\xampp\htdocs\lwt\utilities.inc.php:3238]
#1  splitCheckText(Er war ein wichtiger Politiker für Deutschland, ein Mann, der sich für die Wiedervereinigung einsetzte und weltweit geschätzt wurde. Am 31. März 2016 ist Hans-Dietrich Genscher in der Nähe von Bonn gestorben.

„Wir sind zu Ihnen gekommen, um Ihnen mitzuteilen, dass heute Ihre Ausreise genehmigt wurde.“ Es ist vor allem dieser Satz von Hans-Dietrich Genscher, den man nicht vergessen wird. Er sprach ihn am 30. September 1989 auf dem Balkon der bundesdeutschen Botschaft in Prag. Die letzten Worte gingen im Jubel tausender DDR-Bürger unter, die ihr Land verlassen hatten und seit Tagen im Botschaftsgarten auf ihre Ausreise warteten.

Als Außenminister setzte sich Genscher für ein Ende des Kalten Krieges ein. Als die Sowjetunion in den 1980er Jahren in der DDR innere Reformen erlaubte, forderte Genscher die politische Führung der DDR zum Umdenken auf. Mit der Deutschen Einheit im Jahr 1990 ging für Genscher, der selbst aus Ostdeutschland kam, ein Traum in Erfüllung.

Hans-Dietrich Genscher wurde 1927 in der Nähe von Halle im Osten Deutschlands geboren. 1952 ging er aus der DDR nach Bremen und wurde Anwalt. Als Mitglied der FDP war Genscher von 1969 bis 1974 Bundesinnenminister, von 1974 bis 1992 Bundesaußenminister und gleichzeitig Vizekanzler.

Sein aktives politisches Leben beendete Genscher 1992. Viele Karikaturisten waren darüber sehr traurig: Sie liebten es, den „Dicken mit den großen Ohren“ zu zeichnen. Eine Zeitschrift zeichnete ihn als „Genschman“, als einen Superhelden wie Batman, der jede Krisensituation schafft. Genscher blieb trotzdem Teil der FDP und unterstützte immer wieder junge Politiker, wie zum Beispiel den FDP-Politiker Guido Westerwelle, der Mitte März 2016 gestorben ist. Hans-Dietrich Genscher starb am 31. März 2016. Er wurde 89 Jahre alt.

**Comment by Zireael07** [comment]
April 7? Try redownloading 1.6.28, I recall the download changing twice that day, and one indeed broke like that due to a spurious / or something in regex handling code.

**Comment by dif1754** [comment]
Thanks, I redownloaded the zip file and now it works!
I guess it would be a nice idea to release a new version number, 2.6.28.1 ?, whenever a change is made inside the project, even if little one...
