### ISSUE TITLE
Show sentence

### ISSUE THREAD

**Issue by jasiek123** [andreask7/lwt#3]
Hi! 
There is a problem with LWT version 1.6.10 (and earlier versions also). When reading a text the "Show sentences" link didn't work for new terms. There's no action when I click on it - no other sentences are shown. Also a term in sentence is not marked withing brackets { and }.  But when I choose "Edit term" for existing term the issue didn't happens.
Screenshot for new term:
![screenshot](https://cloud.githubusercontent.com/assets/10896485/6092197/c6843058-aed3-11e4-91bc-f7307480c516.jpg)
Screenshot for existing term:
![screenshot2](https://cloud.githubusercontent.com/assets/10896485/6092232/bfa6cb0e-aed5-11e4-905a-45e72764be67.jpg)

**Comment by andreask7** [comment]
Hi jasiek123!
Bug fixed in version 1.6.11. 'Show sentences' should work now.
Andreas

**Comment by jasiek123** [comment]
Thank you. If I notice any other bugs I'll inform you.
