### ISSUE TITLE
Problem with expressions

### ISSUE THREAD

**Issue by dif1754** [andreask7/lwt#4]
LWT vers. 1.6.12

I tried to insert an expressions with two terms and I got fatal errors (the following). Can you help me please? I normally can save expressions. I don't if it's because of the LWT version or because of the text I pasted...

***************************************************************************************
CASE 1 = translation on an expression with 2 terms.
New Term: in einigen

Fatal Error in SQL Query: insert into words (WoLgID, WoTextLC, WoText, WoStatus, WoTranslation, WoSentence, WoRomanization, WoWordCount, WoStatusChanged, WoTodayScore, WoTomorrowScore, WoRandom ) values( 1, 'in einigen', 'In einigen', 3, 'in alcuni', '{In einigen} Krankenhäusern mussten Operationen verschoben werden – die Ärzte hatten Grippe.', NULL, NULL, NOW(), GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(6.9 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(20 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(46.4 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(100 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 -7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(3.4 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(17.7 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(44.65 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(98.6 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), RAND() )
Error Code & Message: [1048] Column 'WoWordCount' cannot be null
Backtrace:

#0  do_mysql_query(insert into words (WoLgID, WoTextLC, WoText, WoStatus, WoTranslation, WoSentence, WoRomanization, WoWordCount, WoStatusChanged, WoTodayScore, WoTomorrowScore, WoRandom ) values( 1, 'in einigen', 'In einigen', 3, 'in alcuni', '{In einigen} Krankenhäusern mussten Operationen verschoben werden – die Ärzte hatten Grippe.', NULL, NULL, NOW(),  GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(6.9 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(20 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(46.4 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(100 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 -7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(3.4 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(17.7 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(44.65 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(98.6 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), RAND() )) called at [C:\xampp\htdocs\lwt-beta\dbutils.inc.php:63]
#1  runsql(insert into words (WoLgID, WoTextLC, WoText, WoStatus, WoTranslation, WoSentence, WoRomanization, WoWordCount, WoStatusChanged, WoTodayScore, WoTomorrowScore, WoRandom ) values( 1, 'in einigen', 'In einigen', 3, 'in alcuni', '{In einigen} Krankenhäusern mussten Operationen verschoben werden – die Ärzte hatten Grippe.', NULL, NULL, NOW(),  GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(6.9 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(20 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(46.4 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(100 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 -7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(3.4 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(17.7 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(44.65 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(98.6 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), RAND() ), Term saved) called at [C:\xampp\htdocs\lwt-beta\edit_mword.php:79]

********************************************************************************************
CASE 2= ignoring an expresion with 2 terms:

New Term: susanne glasemacher

Fatal Error in SQL Query: insert into words (WoLgID, WoTextLC, WoText, WoStatus, WoTranslation, WoSentence, WoRomanization, WoWordCount, WoStatusChanged, WoTodayScore, WoTomorrowScore, WoRandom ) values( 1, 'susanne glasemacher', 'Susanne Glasemacher', 98, '*', 'Die Gesamtzahl der Erkrankungen ist sicher höher, meint {Susanne Glasemacher} vom RKI: „Wie hoch diese Dunkelziffer genau ist, wissen wir nicht, aber es gibt eine erhebliche Untererfassung.“', NULL, NULL, NOW(), GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(6.9 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(20 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(46.4 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(100 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 -7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(3.4 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(17.7 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(44.65 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(98.6 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), RAND() )
Error Code & Message: [1048] Column 'WoWordCount' cannot be null
Backtrace:

#0  do_mysql_query(insert into words (WoLgID, WoTextLC, WoText, WoStatus, WoTranslation, WoSentence, WoRomanization, WoWordCount, WoStatusChanged, WoTodayScore, WoTomorrowScore, WoRandom ) values( 1, 'susanne glasemacher', 'Susanne Glasemacher', 98, '*', 'Die Gesamtzahl der Erkrankungen ist sicher höher, meint {Susanne Glasemacher} vom RKI: „Wie hoch diese Dunkelziffer genau ist, wissen wir nicht, aber es gibt eine erhebliche Untererfassung.“', NULL, NULL, NOW(),  GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(6.9 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(20 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(46.4 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(100 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 -7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(3.4 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(17.7 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(44.65 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(98.6 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), RAND() )) called at [C:\xampp\htdocs\lwt-beta\dbutils.inc.php:63]
#1  runsql(insert into words (WoLgID, WoTextLC, WoText, WoStatus, WoTranslation, WoSentence, WoRomanization, WoWordCount, WoStatusChanged, WoTodayScore, WoTomorrowScore, WoRandom ) values( 1, 'susanne glasemacher', 'Susanne Glasemacher', 98, '*', 'Die Gesamtzahl der Erkrankungen ist sicher höher, meint {Susanne Glasemacher} vom RKI: „Wie hoch diese Dunkelziffer genau ist, wissen wir nicht, aber es gibt eine erhebliche Untererfassung.“', NULL, NULL, NOW(),  GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(6.9 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(20 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(46.4 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(100 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), GREATEST(-125, CASE WHEN WoStatus > 5 THEN 100 WHEN WoStatus = 1 THEN ROUND(-7 -7 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 2 THEN ROUND(3.4 - 3.5 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 3 THEN ROUND(17.7 - 2.3 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 4 THEN ROUND(44.65 - 1.75 * DATEDIFF(NOW(),WoStatusChanged)) WHEN WoStatus = 5 THEN ROUND(98.6 - 1.4 * DATEDIFF(NOW(),WoStatusChanged)) END), RAND() ), Term saved) called at [C:\xampp\htdocs\lwt-beta\edit_mword.php:79]

**Comment by andreask7** [comment]
I uploaded the bugfix to version 1.6.12.

**Comment by dif1754** [comment]
I just updated LWT and now it works. thanks.
